# Generated by Django 4.2.7 on 2025-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
